### PR TITLE
Basic cleanup

### PR DESCRIPTION
**Pull request by davidfischer-ch**
Hi @bameda,

I am reworking my fork to integrate my work in your repository.

This pull requests contains the basic modifications I made that should not change the behavior of the code. Can you review this please?

Next ones to come.
Thanks.

### CODE REVIEW

**Comment by davidfischer-ch** [comment]
Don't mind the Travis build errors.
There are random travis ConnectionResetError: [Errno 104] Connection reset by peer.

**Comment by bameda** [comment]
I know I've suffered false negatives many times  :-)

**Comment by davidfischer-ch** [comment]
I've used travis_retry into my repository.
It can be worth.

https://github.com/davidfischer-ch/pytoolbox/blob/master/.travis.yml#L10

**Comment by bameda** [comment]
This week I'm kind of busy and don't have much time to review it thoroughly but the next one I'll do, I promise

Thank you very very much for your help :smiley_cat:

**Comment by bameda** [comment]
Thank you very much @davidfischer-ch :dancer:

Merged in https://github.com/bameda/djmail/commit/388b4ddf6b9c62ed9ff91ab9eae89db73919acc9

**Pull request closed without merging**
