### PR TITLE
Celery upgrade, small project re-organize, management command, code update

### PR DESCRIPTION
**Pull request by mathieuhinderyckx**

### CODE REVIEW

**Comment by bameda** [comment]
Hi @mathieuhinderyckx thank you very much for your PR but I have some questions: why did you make these changes? can you explain me your motivations and its benefits? I understand the upgrade to use celery 4.x, but the reorganisation (move test files to the root dir, the division of some lines, remove the encode line in the beggining of some files and the other style changes,....)

**Comment by mathieuhinderyckx** [comment]
The main motivation is some code modernisation and following the Django-recommended ways:

- Moving the status field inside the Message model: [Django Docs: choices](https://docs.djangoproject.com/en/1.10/ref/models/fields/#choices)
- Moving the signal to apps.py/signals.py: [Django Docs: Signals - Where should this code live](https://docs.djangoproject.com/en/1.10/topics/signals/#connecting-receiver-functions)
- Running tests: [Django docs: Running tests](https://docs.djangoproject.com/en/1.10/topics/testing/overview/#running-tests)

Regarding the tests, you could make a point for having a seperate tests directory such as described [here](https://docs.djangoproject.com/en/1.10/topics/testing/advanced/#using-the-django-test-runner-to-test-reusable-applications). However, this is rather obscure compared to just 'python manage.py test' which every Django person/project knows and uses, and the latter also integrates better with coverage and/or other packages.

- Formatting + sorting imports should be done using flake8/pep8. Regarding the encoding line, this was not intentional and is probably the result of other edits.

**Comment by mathieuhinderyckx** [comment]
Any open comments or remarks?

**Comment by bameda** [comment]
Hi @mathieuhinderyckx  and sorry for my delay. I want to make a PR based on yours commits because some of your style changes don't convince me but I have no time this weekend.  

- I prefer chooses as static module vars because Is better to import a vars instead of a class to user it.
- I prefer lines bigger that 79 chars (maybe <100 or <120). Today we have screens with a big resolution that in the pass so this rule has not a lot of sense. I use to apply this rules: https://github.com/taigaio/taiga-back/blob/master/setup.cfg
- I prefer py.test instead of django test because is faster and is more pythonic that Django test module. (http://reinout.vanrees.org/weblog/2014/05/15/pytest.html)
- I prefer to get test in a separate module.
- I prefer to remove dj-database-url. Maybe Is useful for Django project but is an overhead for a Django lib.

I hope I can start next weekend and show you my proposal for your review.

**Comment by mathieuhinderyckx** [comment]
The last 3 issues have been fixed in the last commit. I agree on the second one and will have a look tonight to fix this.

The first one I disagree though. The priority and status variables are all properties of the  Message model and should thus be linked to it. It's also recommended by the Django docs (I linked to the relevant part in the message above).

**Comment by bameda** [comment]
Umm I can live with chooses inside the model class ;-)

**Comment by mathieuhinderyckx** [comment]
I added a part to the asciidocs on the management commands, not sure if I needed to compile something for this to 'deploy'.

Also. while going through the files, I noticed [this line](https://github.com/bameda/djmail/blob/master/djmail/backends/async.py#L45) in the async backend:

```
        @_close_connection_on_finish
        def _send(messages):
            return core._send_messages(email_messages)

        return executor.submit(_send, email_messages)
```

Shouldn't it be ```return core._send_messages(messages)``` instead of ```return core._send_messages(email_messages)``` in the ```_send``` function?

**Comment by bameda** [comment]
Yes, it should be  `return core._send_messages(messages)`

**Comment by bameda** [comment]
Great \o/

I released a new version this weekend.

**Comment by bameda** [comment]
Hi @mathieuhinderyckx 

I've created this PR with your commits https://github.com/bameda/djmail/pull/41. 

- I've updated the version to 1.0.0.
- I've moved `djmail/mocks.py` to `tests/mocks.py`.
- I've compacted some of your commits. 

is it good for you? We can published the new version to PyPI.

**Comment by mathieuhinderyckx** [comment]
Seems good to me!

**Pull request closed without merging**
