### PR TITLE
Add management command + associated tests to cleanup old messages fro…

### PR DESCRIPTION
**Pull request by mathieuhinderyckx**
…m the database.

### CODE REVIEW

**Comment by bameda** [comment]
Cool :+1:

**Comment by bameda** [comment]
I'll do it compatible with Django < 1.8 this weekend and release a new version. Thanks for your PR.

**Comment by mathieuhinderyckx** [comment]
As Django < 1.8 is no longer supported ([Supported Versions](https://www.djangoproject.com/download/#supported-versions)), shouldn't it be better to drop support for these versions alltogether?

**Comment by bameda** [comment]
Ummm you are right. I'll work on this approach.

**Pull request closed without merging**
