### PR TITLE
Premailer: Fix call when html is None + add mix-in

### PR DESCRIPTION
**Pull request by davidfischer-ch**
Review it when you are back.

### CODE REVIEW

**Comment by bameda** [comment]
Ack

**Comment by bameda** [comment]
Hi @davidfischer-ch 

There is an error (python 2.7 / django 1.4.22)

```python
Traceback (most recent call last):
  File "runtests.py", line 13, in <module>
    execute_from_command_line(args)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/test.py", line 49, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/simple.py", line 380, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/simple.py", line 266, in build_suite
    for app in get_apps():
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/loading.py", line 126, in get_apps
    self._populate()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/loading.py", line 67, in _populate
    self.load_app(app_name)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/travis/build/bameda/djmail/djmail/models.py", line 12, in <module>
    from . import utils
  File "/home/travis/build/bameda/djmail/djmail/utils.py", line 13, in <module>
    from django.utils.encoding import force_bytes
ImportError: cannot import name force_bytes
```

Try to fix this, maybe using ```smart_bytes``` if ```force_bytes``` can be imported...

```python
try:
    from django.utils.encoding import force_bytes
except ImportError:
    from django.utils.encoding import smart_bytes as force_bytes
```

**Comment by davidfischer-ch** [comment]
Hi,

Its not an issue related to the code modified by this pull request.
Can you implement your fix into master but before maybe integrate this if it sounds good.

**Comment by bameda** [comment]
it's true. ok, forget what I told you

**Comment by bameda** [comment]
Ok, the error is in your PR https://github.com/bameda/djmail/pull/26

**Comment by bameda** [comment]
Merged in https://github.com/bameda/djmail/commit/df202d2ce348c3ea7e724f785fd0c8bc17568c9a
\
Thanks @davidfischer-ch

**Pull request closed without merging**
